# Generated by Django 3.1.7 on 2021-03-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210319_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('name',), 'verbose_name_plural': '1. Collections'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name_plural': '2. Products'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ('color',), 'verbose_name_plural': '3. ProductColors'},
        ),
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
