# Generated by Django 3.1.7 on 2021-03-20 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210319_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='store.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True),
        ),
    ]
