# Generated by Django 3.1.7 on 2021-03-22 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210319_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ('product__name', 'color'), 'verbose_name_plural': '3. ProductColors'},
        ),
        migrations.RemoveField(
            model_name='picture',
            name='product',
        ),
    ]
