# Generated by Django 3.1.7 on 2021-03-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210322_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ('product__name', 'name'), 'verbose_name_plural': '3. ProductColors'},
        ),
        migrations.RenameField(
            model_name='productcolor',
            old_name='color',
            new_name='name',
        ),
    ]
